-- Grocery Sales Project

DROP TABLE IF EXISTS sales;
CREATE TABLE sales
	(
		Order_ID VARCHAR(12) PRIMARY KEY,	
		date DATE,	
		Customer_Name VARCHAR(20),
		Product VARCHAR(15),
		Category VARCHAR(15),	
		Quantity INT,
		Unit_Price FLOAT,
		Payment_Mode VARCHAR(20)
	);

	
-- Tasks Perform 

--Display all records from the table.

SELECT * FROM sales;

--Display only order_id, date, product, and category.

SELECT order_id,date,product, category 
FROM sales;

--Display all unique product categories.

SELECT DISTINCT product,category
FROM sales;

--Display all unique payment modes.

SELECT DISTINCT(payment_mode)
FROM sales;

--Find the total number of orders.

SELECT COUNT(order_id) FROM sales ;

--Find the total quantity of products sold.

SELECT SUM(quantity) FROM sales;

--Find the highest unit price,lowest unit price and average unit price

SELECT MAX(unit_price), MIN(unit_price), AVG(unit_price)
FROM sales ;


--Display all orders where the category is Fruits and the payment mode is UPI.

SELECT * FROM sales
WHERE category = 'Fruits' AND payment_mode = 'UPI';

--Display all orders where the quantity is greater than 3.

SELECT * FROM sales
WHERE quantity > 3;

--Display all orders where the unit price is between 100 and 500.

SELECT * FROM sales
WHERE unit_price BETWEEN 100 AND 500;

--Display all orders where the product name starts with A.

SELECT * FROM sales 
WHERE product LIKE 'A%';

--Display all orders sorted by unit price from highest to lowest.

SELECT * FROM sales
ORDER BY unit_price DESC;

--Display order_id, product, quantity, unit_price, and calculated sales_amount.

SELECT order_id,product,quantity,unit_price ,quantity*unit_price AS sales_amount
FROM sales ;

--Find the total sales amount of all orders.

SELECT SUM(quantity*unit_price) AS total_sales
FROM sales;

--Find the average sales amount per order.

SELECT AVG(quantity*unit_price) AS average_total_sales
FROM sales;

--Find the highest sales amount generated by a single order.

SELECT MAX(quantity*unit_price) AS max_total_sales
FROM sales;

--Display the top 10 orders based on sales amount.

SELECT order_id,product,quantity,unit_price , quantity*unit_price AS sales_amount
FROM sales 
ORDER BY sales_amount DESC
LIMIT 10;

--Display all orders where the calculated sales amount is greater than 1,000.

SELECT order_id, product, quantity, unit_price , quantity * unit_price AS sales_amount
FROM sales
WHERE quantity * unit_price> 1000;


--Find the total sales amount for each product category.

SELECT category , SUM(quantity * unit_price) AS sales_amount
FROM sales
GROUP BY category;

--Find the total quantity sold for each product category.

SELECT category,SUM(quantity) 
FROM sales
GROUP BY category;

--Find the average unit price for each product category.

SELECT category, AVG(unit_price)
FROM sales
GROUP BY category;
